### ISSUE TITLE
Angular 6.x Peer Dependency Warning from npm

### ISSUE THREAD

**Issue by FergusZhou** [alhazmy13/angular-csv#18]
**Versions**
"@angular/core": "^6.0.2",
"@angular/http": "^6.0.2",
"rxjs": "^6.0.0",

**Repro steps**
npm i

**Observed behavior**
npm WARN angular5-csv@0.2.10 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular5-csv@0.2.10 requires a peer of @angular/http@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular5-csv@0.2.10 requires a peer of rxjs@^5.5.2 but none is installed. You must install peer dependencies yourself.

**Desired behavior**
No peer dependency warnings/errors from npm by using the angular5-csv.

**Mention any other details that might be useful**
```
  "peerDependencies": {
    "@angular/core": "^5.0.0",
    "@angular/http": "^5.0.0",
    "rxjs": "^5.5.2"
  },
```
I can use angular5-csv in Angular 6, but give this npm warn because of above peerDependencies...

**Comment by alhazmy13** [comment]
Fixed with https://github.com/alhazmy13/angular-csv/pull/33

**Comment by kthomas182** [comment]
@alhazmy13 I don't believe the 1.0.0 package is registered on npm.

npm ERR! notarget No matching version found for angular5-csv@1.0.0

It's still showing:
version
0.2.11
https://www.npmjs.com/package/angular5-csv
